version: '3.8'

services:
  backend:
    build: ./Backend/
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/gcloud_creds.json
    volumes:
      - ./Backend:/code/
    ports:
      - 8000:8000
    command: python main.py

  frontend:
    build: ./Extension
    volumes:
      - ./Extension:/code/
    ports:
      - 9090:9090
    command: yarn run dev:chrome:docker
